import { Mime } from "npm:mime";
export { etag } from "npm:hono/etag";
export { logger } from "npm:hono/logger";
export { Magika } from "npm:magika@0.2.5";
export { Hono } from "npm:hono";
import { Context, Env, ToSchema } from "npm:hono";
import otherTypes from "npm:mime/types/other.js";
import standardTypes from "npm:mime/types/standard.js";
import magikaLabelsTypes from "./types/magikaLabelsTypes.ts";
export { fileTypeFromBuffer } from "npm:file-type";
import { FileTypeResult } from "npm:file-type";
export { create } from "https://deno.land/x/ipfs@0.4.0-wip.6/mod.ts";
export { Mime, standardTypes, otherTypes, magikaLabelsTypes };
export type { Context, Env, ToSchema, FileTypeResult };
