version: "3.9"
services:
  ipfs:
    restart: always
    build: .
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      start_period: "30s"
      retries: 10
      timeout: "10s"
      interval: "5s"
    ports:
      - "4001"
      - "4001/udp"
    environment:
      ALLOW_ORIGINS: "*"
    labels:
      - "autoheal=true"
    profiles:
      - main
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 3m

  nginx:
    restart: always
    image: nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      start_period: "30s"
      retries: 10
      timeout: "10s"
      interval: "30s"
    depends_on:
      ipfs:
        condition: service_healthy
    volumes:
      - .:/etc/nginx/conf.d
    labels:
      - "autoheal=true"
    profiles:
      - main
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 3m

  tunnel:
    restart: always
    image: zoeyvid/cloudflared:latest
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9173/metrics || exit 1"]
      start_period: "30s"
      retries: 10
      timeout: "10s"
      interval: "30s"
    depends_on:
      nginx:
        condition: service_healthy
    labels:
      - "autoheal=true"
    profiles:
      - main
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 3m

  netdata:
    restart: always
    image: netdata/netdata
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:19999 || exit 1"]
      start_period: "30s"
      retries: 10
      timeout: "10s"
      interval: "30s"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "autoheal=true"
    profiles:
      - monitor
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 3m

  tunnel-netdata:
    restart: always
    image: zoeyvid/cloudflared:latest
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${NETDATA_TUNNEL_TOKEN}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9173/metrics || exit 1"]
      start_period: "30s"
      retries: 10
      timeout: "10s"
      interval: "30s"
    depends_on:
      netdata:
        condition: service_healthy
    labels:
      - "autoheal=true"
    profiles:
      - monitor
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 3m

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - main
      - monitor
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 3m
