name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            repo="${HOME}/$(basename $(echo ${{ github.event.repository.url }}))"
            if [[ -e ${repo} ]]; then
              cd ${repo} && \
              git pull
            else
              git clone ${{ github.event.repository.url }} && \
              cd ${repo}
            fi
            if type gemster > /dev/null 2>&1; then
              gemster build-up && \
              gemster reload && \
              yes | docker builder prune
            else
              COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 COMPOSE_PROFILES: main,monitor docker-compose up -d --build --scale ipfs=5 && \
              docker-compose exec nginx nginx -s reload && \
              yes | docker builder prune
            fi
      - name: Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          username: Github Actions
          avatar_url: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"
